INSERT INTO tb_category (name, created_at) VALUES ('Clothing and Accessories', now());
INSERT INTO tb_category (name, created_at) VALUES ('Electronics', now());
INSERT INTO tb_category (name, created_at) VALUES ('IT', now());
INSERT INTO tb_category (name, created_at) VALUES ('Furniture', now());
INSERT INTO tb_category (name, created_at) VALUES ('Decoration', now());
INSERT INTO tb_category (name, created_at) VALUES ('Home Appliances', now());
INSERT INTO tb_category (name, created_at) VALUES ('Books', now());
INSERT INTO tb_category (name, created_at) VALUES ('Music', now());
INSERT INTO tb_category (name, created_at) VALUES ('Movies and Series', now());
INSERT INTO tb_category (name, created_at) VALUES ('Games and Consoles', now());
INSERT INTO tb_category (name, created_at) VALUES ('Toys', now());
INSERT INTO tb_category (name, created_at) VALUES ('Babies and Children', now());
INSERT INTO tb_category (name, created_at) VALUES ('Sports and Fitness', now());
INSERT INTO tb_category (name, created_at) VALUES ('Health and Beauty', now());
INSERT INTO tb_category (name, created_at) VALUES ('Cosmetics', now());
INSERT INTO tb_category (name, created_at) VALUES ('Perfumery', now());
INSERT INTO tb_category (name, created_at) VALUES ('Food and Beverages', now());
INSERT INTO tb_category (name, created_at) VALUES ('Wines and Alcoholic Beverages', now());
INSERT INTO tb_category (name, created_at) VALUES ('Natural Products', now());
INSERT INTO tb_category (name, created_at) VALUES ('Food Supplements', now());
INSERT INTO tb_category (name, created_at) VALUES ('Pet Shop', now());
INSERT INTO tb_category (name, created_at) VALUES ('Tools and Construction', now());
INSERT INTO tb_category (name, created_at) VALUES ('Gardening', now());
INSERT INTO tb_category (name, created_at) VALUES ('Automotive', now());
INSERT INTO tb_category (name, created_at) VALUES ('Motorcycle Parts', now());
INSERT INTO tb_category (name, created_at) VALUES ('Bicycles and Accessories', now());
INSERT INTO tb_category (name, created_at) VALUES ('Stationery and Office', now());
INSERT INTO tb_category (name, created_at) VALUES ('Party Items', now());
INSERT INTO tb_category (name, created_at) VALUES ('Gifts and Souvenirs', now());
INSERT INTO tb_category (name, created_at) VALUES ('Watches', now());
INSERT INTO tb_category (name, created_at) VALUES ('Jewelry and Costume Jewelry', now());
INSERT INTO tb_category (name, created_at) VALUES ('Glasses and Lenses', now());
INSERT INTO tb_category (name, created_at) VALUES ('Bags and Suitcases', now());
INSERT INTO tb_category (name, created_at) VALUES ('Footwear', now());
INSERT INTO tb_category (name, created_at) VALUES ('Underwear', now());
INSERT INTO tb_category (name, created_at) VALUES ('Beachwear', now());
INSERT INTO tb_category (name, created_at) VALUES ('Fitness Fashion', now());
INSERT INTO tb_category (name, created_at) VALUES ('Plus Size Fashion', now());
INSERT INTO tb_category (name, created_at) VALUES ('Childrens Fashion', now());
INSERT INTO tb_category (name, created_at) VALUES ('Mens Fashion', now());
INSERT INTO tb_category (name, created_at) VALUES ('Womens Fashion', now());
INSERT INTO tb_category (name, created_at) VALUES ('Sports Products Cleaning', now());
INSERT INTO tb_category (name, created_at) VALUES ('Hygiene Products', now());
INSERT INTO tb_category (name, created_at) VALUES ('Beauty Products', now());
INSERT INTO tb_category (name, created_at) VALUES ('Hair Products', now());
INSERT INTO tb_category (name, created_at) VALUES ('Skin Products', now());
INSERT INTO tb_category (name, created_at) VALUES ('Nail Products', now());
INSERT INTO tb_category (name, created_at) VALUES ('Beard Products', now());
INSERT INTO tb_category (name, created_at) VALUES ('Bath Products', now());
INSERT INTO tb_category (name, created_at) VALUES ('Personal Care Products', now());
INSERT INTO tb_category (name, created_at) VALUES ('Health Products', now());
INSERT INTO tb_category (name, created_at) VALUES ('Wellness Products', now());
INSERT INTO tb_category (name, created_at) VALUES ('Weight Loss Products', now());
INSERT INTO tb_category (name, created_at) VALUES ('Mass Gain Products', now());
INSERT INTO tb_category (name, created_at) VALUES ('Sports Performance Products', now());
INSERT INTO tb_category (name, created_at) VALUES ('Pet Products', now());
INSERT INTO tb_category (name, created_at) VALUES ('Home Products', now());
INSERT INTO tb_category (name, created_at) VALUES ('Kitchen Products', now());
INSERT INTO tb_category (name, created_at) VALUES ('Bath Products', now());
INSERT INTO tb_category (name, created_at) VALUES ('Bedroom Products', now());
INSERT INTO tb_category (name, created_at) VALUES ('Living Room Products', now());
INSERT INTO tb_category (name, created_at) VALUES ('Office Products', now());
INSERT INTO tb_category (name, created_at) VALUES ('Garden Products', now());
INSERT INTO tb_category (name, created_at) VALUES ('Outdoor Products', now());
INSERT INTO tb_category (name, created_at) VALUES ('Pool Products', now());
INSERT INTO tb_category (name, created_at) VALUES ('Barbecue Products', now());
INSERT INTO tb_category (name, created_at) VALUES ('Camping Products', now());
INSERT INTO tb_category (name, created_at) VALUES ('Fishing Products', now());
INSERT INTO tb_category (name, created_at) VALUES ('Cycling Products', now());
INSERT INTO tb_category (name, created_at) VALUES ('Running Products', now());
INSERT INTO tb_category (name, created_at) VALUES ('Swimming Products', now());
INSERT INTO tb_category (name, created_at) VALUES ('Surfing Products', now());
INSERT INTO tb_category (name, created_at) VALUES ('Skateboarding Products', now());
INSERT INTO tb_category (name, created_at) VALUES ('Extreme Sports Products', now());
INSERT INTO tb_category (name, created_at) VALUES ('Team Sports Products', now());
INSERT INTO tb_category (name, created_at) VALUES ('Sports Products Individual', now());
INSERT INTO tb_category (name, created_at) VALUES ('Water Sports Products', now());
INSERT INTO tb_category (name, created_at) VALUES ('Winter Sports Products', now());
INSERT INTO tb_category (name, created_at) VALUES ('Summer Sports Products', now());
INSERT INTO tb_category (name, created_at) VALUES ('Outdoor Sports Products', now());
INSERT INTO tb_category (name, created_at) VALUES ('Indoor Sports Products', now());
INSERT INTO tb_category (name, created_at) VALUES ('Adventure Sports Products', now());
INSERT INTO tb_category (name, created_at) VALUES ('Precision Sports Products', now());
INSERT INTO tb_category (name, created_at) VALUES ('Combat Sports Products', now());
INSERT INTO tb_category (name, created_at) VALUES ('Endurance Sports Products', now());
INSERT INTO tb_category (name, created_at) VALUES ('Speed Sports Products', now());
INSERT INTO tb_category (name, created_at) VALUES ('Strength Sports Products', now());
INSERT INTO tb_category (name, created_at) VALUES ('Agility Sports Products', now());
INSERT INTO tb_category (name, created_at) VALUES ('Flexibility Sports Products', now());
INSERT INTO tb_category (name, created_at) VALUES ('Balance Sports Products', now());
INSERT INTO tb_category (name, created_at) VALUES ('Coordination Sports Products', now());
INSERT INTO tb_category (name, created_at) VALUES ('Endurance Sports Products', now());
INSERT INTO tb_category (name, created_at) VALUES ('Power Sports Products', now());
INSERT INTO tb_category (name, created_at) VALUES ('Technical Sports Products', now());
INSERT INTO tb_category (name, created_at) VALUES ('Strategy Sports Products', now());
INSERT INTO tb_category (name, created_at) VALUES ('Competitive Sports Products', now());
INSERT INTO tb_category (name, created_at) VALUES ('Recreational Sports Products', now());
INSERT INTO tb_category (name, created_at) VALUES ('Leisure Sports Products', now());
INSERT INTO tb_category (name, created_at) VALUES ('Performance Sports Products', now());
INSERT INTO tb_category (name, created_at) VALUES ('High Performance Sports Products', now());